kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata: 
  name: "api"
spec: 
  replicas: 1
  template: 
    metadata: 
      name: "api"
      labels: 
        app: "api"
        track: "stable"
    spec: 
      containers: 
        - name: "api"
          image: gcr.io/difference-between/api:3
          imagePullPolicy: "Always"
          ports: 
            - containerPort: 7000
          livenessProbe: 
            initialDelaySeconds: 30
            httpGet: 
              path: "/status"
              port: 7000
          resources: 
            requests: 
              memory: "100Mi"
          env: 
            - name: "EMAIL_PASS"
              value: ""
            - name: "MONGO_URL"
              value: ""
            - name: "MONGO_USER"
              value: ""
            - name: "MONGO_PASS"
              value: ""

